# Generated by Django 2.2.4 on 2025-04-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='description',
            field=models.CharField(default='NON', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shows',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
